"""
generate_report.py
------------------
Reads the combined CSV produced by the pipeline run and generates
outputs/all_domains_results.md programmatically.

Usage:
    venv/Scripts/python.exe enriched_ontology_matching/generate_report.py
    venv/Scripts/python.exe enriched_ontology_matching/generate_report.py \
        --csv enriched_ontology_matching/outputs/enriched/all_domains_combined.csv \
        --out enriched_ontology_matching/outputs/all_domains_results.md
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

_DIR          = Path(__file__).parent
_CSV_DEFAULT  = _DIR / "outputs" / "enriched" / "all_domains_combined.csv"
_OUT_DEFAULT  = _DIR / "outputs" / "all_domains_results.md"
_TEST_DIR     = _DIR
_NBR_DIR      = _DIR / "outputs" / "neighbourhood"   # neighbourhood coherence CSVs
_LIN_IC_DIR   = _DIR / "outputs" / "lin_ic"          # Lin-IC scoring CSVs
_EMB_DIR      = _DIR / "outputs" / "embeddings"      # sentence embedding CSVs


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_csv(path: Path) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _load_neighbourhood_index(nbr_dir: Path) -> dict[str, list[dict]]:
    """
    Scan nbr_dir for *_coherence.csv files and return a dict mapping
    the domain key stem (e.g. 'auto_V1_V2') to its rows.
    Falls back gracefully if the directory or files are missing.
    """
    index: dict[str, list[dict]] = {}
    if not nbr_dir.is_dir():
        return index
    for f in nbr_dir.glob("*_coherence.csv"):
        key = f.stem.replace("_coherence", "")
        with open(f, newline="", encoding="utf-8") as fh:
            index[key] = list(csv.DictReader(fh))
    return index


def _find_neighbourhood(domain_key: str,
                        nbr_index: dict[str, list[dict]]) -> list[dict]:
    """
    Try to match a combined-CSV domain key to a neighbourhood CSV key.
    Matching is case-insensitive and strips the 'test_' prefix.
    """
    # Build a lower-cased lookup once
    lower_index = {k.lower(): v for k, v in nbr_index.items()}
    for candidate in [
        domain_key,
        domain_key.replace("test_", ""),
    ]:
        hit = lower_index.get(candidate.lower())
        if hit is not None:
            return hit
    return []


def _load_lin_ic_index(lin_ic_dir: Path) -> dict[str, list[dict]]:
    """
    Scan lin_ic_dir for *_lin_ic.csv files and return a dict mapping
    the domain key (e.g. 'auto_V1_V2') to its rows.
    """
    index: dict[str, list[dict]] = {}
    if not lin_ic_dir.is_dir():
        return index
    for f in lin_ic_dir.glob("*_lin_ic.csv"):
        key = f.stem.replace("_lin_ic", "")
        with open(f, newline="", encoding="utf-8") as fh:
            index[key] = list(csv.DictReader(fh))
    return index


def _find_lin_ic(domain_key: str,
                 lin_ic_index: dict[str, list[dict]]) -> list[dict]:
    """Case-insensitive lookup of Lin-IC rows for a given domain key."""
    lower_index = {k.lower(): v for k, v in lin_ic_index.items()}
    for candidate in [domain_key, domain_key.replace("test_", "")]:
        hit = lower_index.get(candidate.lower())
        if hit is not None:
            return hit
    return []


def _load_emb_index(emb_dir: Path) -> dict[str, list[dict]]:
    """
    Scan emb_dir for *_emb.csv files and return a dict mapping
    the domain key (e.g. 'auto_V1_V2') to its rows.
    """
    index: dict[str, list[dict]] = {}
    if not emb_dir.is_dir():
        return index
    for f in emb_dir.glob("*_emb.csv"):
        key = f.stem.replace("_emb", "")
        with open(f, newline="", encoding="utf-8") as fh:
            index[key] = list(csv.DictReader(fh))
    return index


def _find_emb(domain_key: str, emb_index: dict[str, list[dict]]) -> list[dict]:
    """Case-insensitive lookup of embedding rows for a given domain key."""
    lower_index = {k.lower(): v for k, v in emb_index.items()}
    for candidate in [domain_key, domain_key.replace("test_", "")]:
        hit = lower_index.get(candidate.lower())
        if hit is not None:
            return hit
    return []


def _load_domain_meta(domain_key: str) -> dict:
    """
    Return ontology metadata from the test JSON for a given domain key.
    Checks the pairs/ subdirectory first (generated by run_all_pairs.py),
    then falls back to the enriched_ontology_matching root.
    Returns default values if no matching file is found.
    """
    # Check pairs/ subdir first (run_all_pairs.py stores them there)
    test_file = _TEST_DIR / "pairs" / f"{domain_key}.json"
    if not test_file.exists():
        test_file = _TEST_DIR / f"{domain_key}.json"
    meta = {"name_a": domain_key + "_a", "name_b": domain_key + "_b",
            "entities_a": "?", "entities_b": "?",
            "assocs_a": 0, "assocs_b": 0}
    if not test_file.exists():
        return meta
    try:
        data = json.loads(test_file.read_text(encoding="utf-8"))
        ja = data.get("json_a", {})
        jb = data.get("json_b", {})
        meta["name_a"] = ja.get("modelName") or ja.get("ontology_name") or domain_key + "_a"
        meta["name_b"] = jb.get("modelName") or jb.get("ontology_name") or domain_key + "_b"
        meta["entities_a"] = len(ja.get("entities", []))
        meta["entities_b"] = len(jb.get("entities", []))
        meta["assocs_a"]   = len(ja.get("associations", []))
        meta["assocs_b"]   = len(jb.get("associations", []))
    except Exception:
        pass
    return meta


def _tbl_row(*cells: str, widths: list[int] | None = None) -> str:
    if widths:
        cells = [str(c).ljust(w) for c, w in zip(cells, widths)]
    return "| " + " | ".join(str(c) for c in cells) + " |"


def _md_table(headers: list[str], rows: list[list]) -> str:
    col_widths = [max(len(h), max((len(str(r[i])) for r in rows), default=0))
                  for i, h in enumerate(headers)]
    lines = [
        _tbl_row(*headers, widths=col_widths),
        "|" + "|".join("-" * (w + 2) for w in col_widths) + "|",
    ]
    for row in rows:
        lines.append(_tbl_row(*[str(c) for c in row], widths=col_widths))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Neighbourhood coherence subsection
# ---------------------------------------------------------------------------

def _neighbourhood_section(nbr_rows: list[dict], threshold: float = 0.5) -> str:
    """
    Render a Neighbourhood Coherence subsection from the coherence CSV rows.
    """
    if not nbr_rows:
        return ""

    supported = [r for r in nbr_rows
                 if float(r.get("coherence_sym") or 0) >= threshold
                 and (int(r.get("n_nbrs_a") or 0) > 0
                      and int(r.get("n_nbrs_b") or 0) > 0)]
    isolated_a = [r for r in nbr_rows if int(r.get("n_nbrs_a") or 0) == 0]
    isolated_b = [r for r in nbr_rows if int(r.get("n_nbrs_b") or 0) == 0]
    low = [r for r in nbr_rows
           if float(r.get("coherence_sym") or 0) < threshold
           and int(r.get("n_nbrs_a") or 0) > 0
           and int(r.get("n_nbrs_b") or 0) > 0]

    lines: list[str] = []
    lines.append(f"### Layer 0 — Neighbourhood Coherence "
                 f"({len(nbr_rows)} matched pairs analysed)\n")
    lines.append(
        f"Threshold: {threshold} &nbsp;|&nbsp; "
        f"**Supported** (sym >= {threshold}): **{len(supported)}** &nbsp;|&nbsp; "
        f"Low coherence: {len(low)} &nbsp;|&nbsp; "
        f"Isolated in A: {len(isolated_a)} &nbsp;|&nbsp; "
        f"Isolated in B: {len(isolated_b)}\n"
    )

    if supported:
        lines.append("**Neighbourhood-supported matches** "
                     "(name match confirmed by local graph context):\n")
        tbl = []
        for r in sorted(supported,
                        key=lambda x: float(x.get("coherence_sym") or 0),
                        reverse=True):
            tbl.append([
                r["entity_a"], r["entity_b"],
                r.get("semantic_label", ""),
                r.get("coherence_a2b", ""), r.get("coherence_b2a", ""),
                r.get("coherence_sym", ""),
                r.get("avg_best_a2b", ""), r.get("avg_best_b2a", ""),
                r.get("verb_coherence", ""),
                r.get("best_pairs", "")[:60],
            ])
        lines.append(_md_table(
            ["Entity A", "Entity B", "Semantic",
             "Coh_A2B", "Coh_B2A", "Coh_sym",
             "AvgBest_A2B", "AvgBest_B2A", "VerbCoh", "Best neighbour pairs"],
            tbl,
        ))
        lines.append("")

    if low:
        lines.append("**Low-coherence matches** "
                     "(name match but neighbourhood disagrees):\n")
        tbl = []
        for r in sorted(low,
                        key=lambda x: float(x.get("coherence_sym") or 0)):
            tbl.append([
                r["entity_a"], r["entity_b"],
                r.get("semantic_label", ""),
                r.get("coherence_sym", ""),
                r.get("n_nbrs_a", ""), r.get("n_nbrs_b", ""),
                r.get("best_pairs", "")[:50],
            ])
        lines.append(_md_table(
            ["Entity A", "Entity B", "Semantic", "Coh_sym",
             "Nbrs_A", "Nbrs_B", "Best neighbour pairs"],
            tbl,
        ))
        lines.append("")

    if isolated_a:
        ent_list = ", ".join(r["entity_a"] for r in isolated_a[:15])
        if len(isolated_a) > 15:
            ent_list += f" … (+{len(isolated_a)-15} more)"
        lines.append(f"**Isolated in A** (no graph edges — name-only matches): "
                     f"{ent_list}\n")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Lin-IC subsection
# ---------------------------------------------------------------------------

def _lin_ic_section(lin_rows: list[dict]) -> str:
    """
    Render Layer 3 — Lin-IC Final Scoring subsection.

    Shows L1 matches ranked by max_lin_ic and top L2 equivalence
    candidates re-ranked by max_lin_ic.  Flags matches where lin_ic
    is high but ic_lcs is low (generic LCS = weak evidence).
    """
    if not lin_rows:
        return ""

    l1_rows = [r for r in lin_rows if r.get("layer") == "1"]
    l2_rows = [r for r in lin_rows if r.get("layer") == "2"
               and r.get("semantic_label") in ("Identical", "Synonym", "Near-Synonym")]

    if not l1_rows and not l2_rows:
        return ""

    IC_LCS_SPECIFIC = 5.0   # threshold: IC(LCS) >= 5 = specific ancestor

    lines: list[str] = []
    lines.append("### Layer 3 — Lin-IC Final Scoring\n")
    lines.append(
        "IC corpus: Brown (Resnik add-1 smoothing)  &nbsp;|&nbsp; "
        "**High ic_lcs** (>= 5): specific common ancestor = strong match  &nbsp;|&nbsp; "
        "**Low ic_lcs** (< 3): only a generic root links the tokens = weak evidence\n"
    )

    # ── L1 matches ────────────────────────────────────────────────────────
    if l1_rows:
        non_trivial = [r for r in l1_rows
                       if r.get("entity_a", "").lower() != r.get("entity_b", "").lower()]
        if non_trivial:
            lines.append("**L1 non-trivial matches ranked by Lin-IC:**\n")
            ranked = sorted(
                non_trivial,
                key=lambda r: float(r.get("max_lin_ic") or 0),
                reverse=True,
            )
            tbl = []
            for r in ranked:
                ic_lcs_v = float(r.get("ic_lcs") or 0)
                flag = " *" if ic_lcs_v >= IC_LCS_SPECIFIC else (
                       " ?" if ic_lcs_v < 3 else "")
                lcs_display = r.get("lcs", "")[:28]
                tbl.append([
                    r["entity_a"], r["entity_b"],
                    r.get("semantic_label", ""),
                    r.get("wup_score", ""), r.get("max_wup", ""),
                    r.get("lin_ic", ""), r.get("max_lin_ic", ""), r.get("avg_lin_ic", ""),
                    lcs_display, f"{ic_lcs_v:.2f}{flag}",
                ])
            lines.append(_md_table(
                ["Entity A", "Entity B", "Semantic",
                 "WUP", "MaxWUP",
                 "LinIC", "MaxLinIC", "AvgLinIC",
                 "LCS (common ancestor)", "IC(LCS)"],
                tbl,
            ))
            lines.append(
                "\n_* IC(LCS) >= 5: specific ancestor — "
                "? IC(LCS) < 3: generic ancestor only_\n"
            )

    # ── L2 equivalence candidates ──────────────────────────────────────────
    if l2_rows:
        lines.append("**Top L2 equivalence candidates by Lin-IC:**\n")
        ranked_l2 = sorted(
            l2_rows,
            key=lambda r: float(r.get("max_lin_ic") or 0),
            reverse=True,
        )[:15]
        tbl = []
        for r in ranked_l2:
            ic_lcs_v = float(r.get("ic_lcs") or 0)
            flag = " *" if ic_lcs_v >= IC_LCS_SPECIFIC else (
                   " ?" if ic_lcs_v < 3 else "")
            tbl.append([
                r["entity_a"], r["entity_b"],
                r.get("semantic_label", ""),
                r.get("lin_ic", ""), r.get("max_lin_ic", ""), r.get("avg_lin_ic", ""),
                r.get("lcs", "")[:28], f"{ic_lcs_v:.2f}{flag}",
            ])
        lines.append(_md_table(
            ["Entity A", "Entity B", "Semantic",
             "LinIC", "MaxLinIC", "AvgLinIC",
             "LCS (common ancestor)", "IC(LCS)"],
            tbl,
        ))
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Embedding cosine similarity subsection
# ---------------------------------------------------------------------------

def _embedding_section(emb_rows: list[dict]) -> str:
    """
    Render Layer 4 — Sentence Embedding Cosine Similarity subsection.

    Shows L1 non-trivial matches and top L2 equivalence candidates ranked
    by cosine_avg.  Three representations are reported:
      whole : encode(full readable name)
      sum   : normalize(sum of token embeddings)
      prod  : normalize(element-wise product of token embeddings)
    """
    if not emb_rows:
        return ""

    l1_rows = [r for r in emb_rows if r.get("layer") == "1"]
    l2_rows = [r for r in emb_rows if r.get("layer") == "2"
               and r.get("semantic_label") in ("Identical", "Synonym", "Near-Synonym")]

    if not l1_rows and not l2_rows:
        return ""

    lines: list[str] = []
    lines.append("### Layer 4 — Sentence Embedding Similarity\n")
    lines.append(
        "Model: `paraphrase-MiniLM-L6-v2` (L2-normalised cosine)  &nbsp;|&nbsp; "
        "**whole**: holistic CamelCase name  &nbsp;|&nbsp; "
        "**sum**: sum of token embeddings  &nbsp;|&nbsp; "
        "**prod**: element-wise product of token embeddings  &nbsp;|&nbsp; "
        "**avg**: mean of the three\n"
    )

    # L1 non-trivial matches ranked by cosine_avg
    if l1_rows:
        non_trivial = [r for r in l1_rows
                       if r.get("entity_a", "").lower() != r.get("entity_b", "").lower()]
        if non_trivial:
            lines.append("**L1 non-trivial matches ranked by cosine avg:**\n")
            ranked = sorted(
                non_trivial,
                key=lambda r: float(r.get("cosine_avg") or 0),
                reverse=True,
            )
            tbl = []
            for r in ranked:
                tbl.append([
                    r["entity_a"], r["entity_b"],
                    r.get("semantic_label", ""),
                    r.get("cosine_whole", ""), r.get("cosine_sum", ""),
                    r.get("cosine_prod", ""), r.get("cosine_avg", ""),
                    r.get("tokens_a", ""), r.get("tokens_b", ""),
                ])
            lines.append(_md_table(
                ["Entity A", "Entity B", "Semantic",
                 "Cos_whole", "Cos_sum", "Cos_prod", "Cos_avg",
                 "Tokens A", "Tokens B"],
                tbl,
            ))
            lines.append("")

    # L2 equivalence candidates ranked by cosine_avg (top 15)
    if l2_rows:
        lines.append("**Top L2 equivalence candidates by cosine avg:**\n")
        ranked_l2 = sorted(
            l2_rows,
            key=lambda r: float(r.get("cosine_avg") or 0),
            reverse=True,
        )[:15]
        tbl = []
        for r in ranked_l2:
            tbl.append([
                r["entity_a"], r["entity_b"],
                r.get("semantic_label", ""),
                r.get("cosine_whole", ""), r.get("cosine_sum", ""),
                r.get("cosine_prod", ""), r.get("cosine_avg", ""),
                r.get("tokens_a", ""), r.get("tokens_b", ""),
            ])
        lines.append(_md_table(
            ["Entity A", "Entity B", "Semantic",
             "Cos_whole", "Cos_sum", "Cos_prod", "Cos_avg",
             "Tokens A", "Tokens B"],
            tbl,
        ))
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-domain section builder
# ---------------------------------------------------------------------------

def _domain_section(domain: str, rows: list[dict], meta: dict, idx: int,
                    nbr_rows: list[dict] | None = None,
                    lin_ic_rows: list[dict] | None = None,
                    emb_rows: list[dict] | None = None) -> str:
    l1    = [r for r in rows if r["layer"] == "1"]
    l2eq  = [r for r in rows if r["layer"] == "2" and r["layer2_type"] == "Equivalence"]
    l2sub = [r for r in rows if r["layer"] == "2" and r["layer2_type"] == "Subsumption"]
    l2cn  = [r for r in rows if r["layer"] == "2"
             and r["layer2_type"] not in ("Equivalence", "Subsumption", "None", "")]

    aml_only  = sum(1 for r in l1 if r["source"] == "AML")
    lm_only   = sum(1 for r in l1 if r["source"] == "LogMap")
    both      = sum(1 for r in l1 if r["source"] == "Both")

    name_a = meta["name_a"]
    name_b = meta["name_b"]
    ents_a = meta["entities_a"]
    ents_b = meta["entities_b"]

    lines: list[str] = []
    lines.append(f"\n---\n")
    lines.append(f"## Domain {idx}: {name_a} vs {name_b}\n")
    lines.append(f"**Ontology A**: {ents_a} entities &nbsp;|&nbsp; "
                 f"**Ontology B**: {ents_b} entities\n")

    # ── Neighbourhood coherence (if available) ───────────────────────────────
    if nbr_rows:
        lines.append(_neighbourhood_section(nbr_rows))

    # ── Layer 1 ──────────────────────────────────────────────────────────────
    lines.append(f"### Layer 1 — Structural matcher results ({len(l1)} matched pairs)\n")
    lines.append(f"AML: {aml_only + both} &nbsp;|&nbsp; "
                 f"LogMap: {lm_only + both} &nbsp;|&nbsp; "
                 f"Both: {both} &nbsp;|&nbsp; Merged unique: {len(l1)}\n")

    # Semantic label distribution
    sem_counts: dict[str, int] = defaultdict(int)
    for r in l1:
        sem_counts[r["semantic_label"]] += 1
    dist_rows = sorted(sem_counts.items(), key=lambda x: -x[1])
    lines.append(_md_table(["Semantic Label", "Count"],
                            [[lbl, cnt] for lbl, cnt in dist_rows]))
    lines.append("")

    # Non-trivial / low-confidence matches — exclude pairs where entity names
    # are identical (those are structural trivial matches, never interesting).
    non_trivial = [r for r in l1
                   if r["entity_a"].lower() != r["entity_b"].lower()]
    low_conf    = [r for r in l1
                   if r["entity_a"].lower() == r["entity_b"].lower()
                   and float(r["matcher_conf"] or 0) < 0.85]
    interesting = non_trivial + low_conf

    if interesting:
        lines.append("**Non-trivial matches (different entity names):**\n")
        tbl = [[r["entity_a"], r["entity_b"], r["source"],
                r["matcher_conf"], r["semantic_label"],
                r["wup_score"], r.get("max_wup", ""), r.get("avg_wup", "")]
               for r in interesting]
        lines.append(_md_table(
            ["Entity A", "Entity B", "Src", "Conf", "Semantic", "WUP", "MaxWUP", "AvgWUP"],
            tbl,
        ))
        lines.append("")

    # ── Layer 2 equivalences ─────────────────────────────────────────────────
    lines.append(f"### Layer 2 — New equivalence candidates ({len(l2eq)})\n")
    if l2eq:
        tbl = [[r["entity_a"], r["entity_b"], r["semantic_label"],
                r["wup_score"], r.get("max_wup", ""), r.get("avg_wup", ""),
                f"{r['token_a']} / {r['token_b']}"]
               for r in l2eq]
        lines.append(_md_table(
            ["Entity A", "Entity B", "Semantic", "WUP", "MaxWUP", "AvgWUP", "Tokens"],
            tbl,
        ))
    else:
        lines.append("_None found._")
    lines.append("")

    # ── Layer 2 subsumptions ─────────────────────────────────────────────────
    # Sort by max_wup when available, fall back to wup_score
    top_sub = sorted(
        l2sub,
        key=lambda r: float(r.get("max_wup") or r.get("wup_score") or 0),
        reverse=True,
    )[:10]
    lines.append(f"### Layer 2 — Subsumption candidates ({len(l2sub)}, top 10 by MaxWUP)\n")
    if top_sub:
        tbl = [[r["entity_a"], r["entity_b"], r["wn_relation"],
                r["wup_score"], r.get("max_wup", ""), r.get("avg_wup", ""),
                f"{r['token_a']} / {r['token_b']}"]
               for r in top_sub]
        lines.append(_md_table(
            ["Entity A", "Entity B", "WN Relation", "WUP", "MaxWUP", "AvgWUP", "Tokens"],
            tbl,
        ))
    else:
        lines.append("_None found._")
    lines.append("")

    # ── Layer 2 CN-backed relations ──────────────────────────────────────────
    lines.append(f"### Layer 2 — ConceptNet-backed relations ({len(l2cn)})\n")
    if l2cn:
        tbl = [[r["entity_a"], r["entity_b"], r["cn_label"],
                r["wup_score"], r.get("max_wup", ""), r.get("avg_wup", ""),
                f"{r['token_a']} / {r['token_b']}"]
               for r in l2cn]
        lines.append(_md_table(
            ["Entity A", "Entity B", "CN Relation", "WUP", "MaxWUP", "AvgWUP", "Tokens"],
            tbl,
        ))
    else:
        lines.append("_None found._")
    lines.append("")

    # ── Layer 3: Lin-IC final scoring ────────────────────────────────────────
    if lin_ic_rows:
        lines.append(_lin_ic_section(lin_ic_rows))

    # ── Layer 4: Sentence embedding cosine similarity ─────────────────────────
    if emb_rows:
        lines.append(_embedding_section(emb_rows))

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Summary table
# ---------------------------------------------------------------------------

def _summary_table(by_domain: dict[str, list[dict]],
                   metas: dict[str, dict]) -> str:
    headers = ["Domain", "O1 Entities", "O2 Entities",
               "L1 Matches", "AML", "LogMap", "Both",
               "L2 Equiv", "L2 Subs", "L2 CN-Rel", "Total Rows"]
    rows = []
    totals = [0] * (len(headers) - 1)

    for domain, drows in by_domain.items():
        meta  = metas[domain]
        l1    = [r for r in drows if r["layer"] == "1"]
        l2eq  = [r for r in drows if r["layer"] == "2" and r["layer2_type"] == "Equivalence"]
        l2sub = [r for r in drows if r["layer"] == "2" and r["layer2_type"] == "Subsumption"]
        l2cn  = [r for r in drows if r["layer"] == "2"
                 and r["layer2_type"] not in ("Equivalence", "Subsumption", "None", "")]

        aml   = sum(1 for r in l1 if r["source"] in ("AML", "Both"))
        lm    = sum(1 for r in l1 if r["source"] in ("LogMap", "Both"))
        both  = sum(1 for r in l1 if r["source"] == "Both")

        vals = [meta["entities_a"], meta["entities_b"],
                len(l1), aml, lm, both,
                len(l2eq), len(l2sub), len(l2cn), len(drows)]
        short = domain.replace("test_", "").replace("_", " ")
        rows.append([short] + vals)
        for i, v in enumerate(vals):
            try:
                totals[i] += int(v)
            except (ValueError, TypeError):
                pass

    rows.append(["**TOTAL**"] + [""] * 2 +
                [f"**{totals[i]}**" for i in range(2, len(totals))])
    return _md_table(headers, rows)


# ---------------------------------------------------------------------------
# Cross-domain observations
# ---------------------------------------------------------------------------

def _cross_domain_obs(by_domain: dict[str, list[dict]]) -> str:
    lines = ["\n---\n", "## Cross-Domain Observations\n"]

    # Label distribution across all domains
    all_rows = [r for drows in by_domain.values() for r in drows]
    l2_rows  = [r for r in all_rows if r["layer"] == "2"]

    sem_all: dict[str, int] = defaultdict(int)
    for r in all_rows:
        sem_all[r["semantic_label"]] += 1

    lines.append("### Semantic label distribution across all domains and layers\n")
    dist = sorted(sem_all.items(), key=lambda x: -x[1])
    lines.append(_md_table(["Label", "Count", "% of total"],
                            [[lbl, cnt, f"{100*cnt/len(all_rows):.1f}%"]
                             for lbl, cnt in dist]))
    lines.append("")

    # L1 source breakdown
    lines.append("### Structural matcher coverage per domain\n")
    src_rows = []
    for domain, drows in by_domain.items():
        l1 = [r for r in drows if r["layer"] == "1"]
        aml  = sum(1 for r in l1 if r["source"] in ("AML", "Both"))
        lm   = sum(1 for r in l1 if r["source"] in ("LogMap", "Both"))
        both = sum(1 for r in l1 if r["source"] == "Both")
        short = domain.replace("test_", "").replace("_", " ")
        src_rows.append([short, len(l1), aml, lm, both,
                         f"{100*both/len(l1):.0f}%" if l1 else "—"])
    lines.append(_md_table(
        ["Domain", "Total L1", "AML", "LogMap", "Both", "Overlap %"],
        src_rows))
    lines.append("")

    # CN relation type breakdown across L2
    cn_rel_counts: dict[str, int] = defaultdict(int)
    for r in l2_rows:
        if r["cn_label"] and r["cn_label"] not in ("None", ""):
            cn_rel_counts[r["cn_label"]] += 1
    if cn_rel_counts:
        lines.append("### ConceptNet relation types found (Layer 2)\n")
        rel_dist = sorted(cn_rel_counts.items(), key=lambda x: -x[1])
        lines.append(_md_table(["CN Relation", "Count"],
                                [[rel, cnt] for rel, cnt in rel_dist]))
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate(csv_path: Path, out_path: Path,
             nbr_dir: Path | None = None,
             lin_ic_dir: Path | None = None,
             emb_dir: Path | None = None) -> None:
    rows     = _load_csv(csv_path)
    by_domain: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_domain[r["domain"]].append(r)

    metas = {d: _load_domain_meta(d) for d in by_domain}

    # Load neighbourhood coherence, Lin-IC, and embedding CSVs
    nbr_index    = _load_neighbourhood_index(nbr_dir or _NBR_DIR)
    lin_ic_index = _load_lin_ic_index(lin_ic_dir or _LIN_IC_DIR)
    emb_index    = _load_emb_index(emb_dir or _EMB_DIR)
    nbr_found    = len(nbr_index)
    lin_found    = len(lin_ic_index)
    emb_found    = len(emb_index)

    cn_info = "5.7.0 local CSV"

    lines: list[str] = [
        "# Enriched Ontology Matching — All Domains Results\n",
        f"**Pipeline**: AML + LogMap (structural) "
        f"-> Layer 1 characterisation (WN+CN) -> Layer 2 discovery (WN+CN) "
        f"-> Layer 3 Lin-IC scoring -> Layer 4 sentence embedding similarity  ",
        f"**ConceptNet**: {cn_info}  ",
        f"**Combined output**: `{csv_path.name}` ({len(rows)} total rows)  ",
        f"**Neighbourhood coherence**: {nbr_found} pair(s) &nbsp;|&nbsp; "
        f"**Lin-IC scored**: {lin_found} pair(s) &nbsp;|&nbsp; "
        f"**Embedding scored**: {emb_found} pair(s)\n",
        "---\n",
        "## Summary\n",
        _summary_table(by_domain, metas),
        "",
    ]

    for idx, (domain, drows) in enumerate(by_domain.items(), start=1):
        nbr_rows    = _find_neighbourhood(domain, nbr_index)
        lin_ic_rows = _find_lin_ic(domain, lin_ic_index)
        emb_rows    = _find_emb(domain, emb_index)
        lines.append(_domain_section(domain, drows, metas[domain], idx,
                                     nbr_rows=nbr_rows,
                                     lin_ic_rows=lin_ic_rows,
                                     emb_rows=emb_rows))

    lines.append(_cross_domain_obs(by_domain))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[Report] Written {len(rows)} rows -> {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate MD report from combined enriched-matcher CSV."
    )
    parser.add_argument("--csv", default=str(_CSV_DEFAULT),
                        help="Path to all_domains_combined.csv")
    parser.add_argument("--out", default=str(_OUT_DEFAULT),
                        help="Output .md file path")
    parser.add_argument("--neighbourhood-dir", default=None,
                        help="Directory containing *_coherence.csv files "
                             f"(default: {_NBR_DIR})")
    parser.add_argument("--lin-ic-dir", default=None,
                        help="Directory containing *_lin_ic.csv files "
                             f"(default: {_LIN_IC_DIR})")
    parser.add_argument("--emb-dir", default=None,
                        help="Directory containing *_emb.csv files "
                             f"(default: {_EMB_DIR})")
    args = parser.parse_args()
    generate(Path(args.csv), Path(args.out),
             nbr_dir=Path(args.neighbourhood_dir) if args.neighbourhood_dir else None,
             lin_ic_dir=Path(args.lin_ic_dir) if args.lin_ic_dir else None,
             emb_dir=Path(args.emb_dir) if args.emb_dir else None)
